# Use postgres/example user/password credentials
version: '3'

services:

  postgres:
    image: postgres
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  adminer:
    image: adminer
    ports:
      - 8080:${ADMINER_PORT}
