# Generated by Django 3.0.2 on 2020-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDbBasics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(help_text='Alphanumeric unique identifier of the title.', max_length=255)),
                ('title_type', models.CharField(help_text='The type/format of the title (e.g. movie, short, tvseries, tvepisode, video, etc).', max_length=255)),
                ('primary_title', models.CharField(help_text='The more popular title / the title used by the filmmakers on promotional materials at the point of release.', max_length=255)),
                ('original_title', models.CharField(help_text='Original title, in the original language.', max_length=255)),
                ('is_adult', models.BooleanField(help_text='Non-adult/adult title.')),
                ('start_year', models.CharField(help_text='Represents the release year of a title. In the case of TV Series, it is the series start year (YYYY).', max_length=4)),
                ('end_year', models.CharField(blank=True, help_text='TV Series end year. \\N for all other title types. (YYYY)', max_length=255, null=True)),
                ('runtime_minutes', models.CharField(blank=True, help_text='Primary runtime of the title, in minutes.', max_length=255, null=True)),
                ('genres', models.CharField(help_text='Includes up to three genres associated with the title.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IMDbEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(help_text='Alphanumeric identifier of episode.', max_length=255)),
                ('parent_tconst', models.CharField(help_text='Alphanumeric identifier of the parent TV Series.', max_length=255)),
                ('season_number', models.IntegerField(help_text='Season number the episode belongs to.')),
                ('episode_number', models.IntegerField(help_text='Episode number of the tconst in the TV series.')),
            ],
        ),
        migrations.CreateModel(
            name='IMDbRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(help_text='Alphanumeric unique identifier of the title.', max_length=255, unique=True)),
                ('average_rating', models.FloatField(help_text='Weighted average of all the individual user ratings.')),
                ('num_votes', models.IntegerField(help_text='Number of votes the title has received.')),
            ],
        ),
    ]
