# Generated by Django 3.0.2 on 2020-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbbasics',
            name='genres',
            field=models.CharField(blank=True, help_text='Includes up to three genres associated with the title.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imdbbasics',
            name='title_type',
            field=models.CharField(choices=[('tvSeries', 'TV Series'), ('tvEpisode', 'TV Episode')], help_text='The type/format of the title (e.g. movie, short, tvseries, tvepisode, video, etc).', max_length=255),
        ),
    ]
