# Generated by Django 3.0.8 on 2020-07-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20200106_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('season_number', 'episode_number')},
        ),
    ]
