# Generated by Django 3.0.8 on 2020-07-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20200707_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.OneToOneField(db_constraint=False, help_text='Alphanumeric identifier of episode.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='imdb.Title'),
        ),
    ]
