# Generated by Django 3.0.2 on 2020-01-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imdb', '0002_auto_20200106_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imdb.Title')),
            ],
        ),
    ]
